name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-15
    env:
      XCODE_VERSION: 16
      dotnetVersion: 9.0.100

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Select Xcode ${{ env.XCODE_VERSION }}
        run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app

      - run: |
          mkdir artifacts
        name: Create Artifacts Directory

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnetVersion }}
   
      - name: Install Workloads
        run: dotnet workload install ios maccatalyst --version $dotnetVersion
        env:
          dotnetVersion: ${{ env.dotnetVersion }}

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - name: Bootstrap carthage deps
        run: |
          mkdir -p artfifacts
          sh carthage.sh update --use-xcframeworks --platform iOS --log-path artifacts/carthage.log
        continue-on-error: true

      - name: Disable SwiftLint in Nuke
        run: |
          echo 'exit 0' > Carthage/Checkouts/Nuke/Scripts/lint.sh
          echo 'exit 0' > Carthage/Checkouts/Nuke/Scripts/validate.sh

      - name: Build Nuke XCFramework
        run: sh carthage.sh build --use-xcframeworks --platform iOS --log-path artifacts/carthage.log

      - name: Build NukeProxy XCFramework
        run: |
          xcodebuild archive -sdk iphoneos -project NukeProxy.xcodeproj -scheme NukeProxy -configuration Release -archivePath Output/Output-iphoneos SKIP_INSTALL=NO
          xcodebuild archive -sdk iphonesimulator -project NukeProxy.xcodeproj -scheme NukeProxy -configuration Release -archivePath Output/Output-iphonesimulator SKIP_INSTALL=NO

          xcodebuild -create-xcframework -framework Output/Output-iphonesimulator.xcarchive/Products/Library/Frameworks/NukeProxy.framework -framework Output/Output-iphoneos.xcarchive/Products/Library/Frameworks/NukeProxy.framework -output Output/NukeProxy.xcframework

      - name: Build Binding Library
        run: dotnet build src/ImageCaching.Nuke/ImageCaching.Nuke.csproj /p:Configuration=Release /p:Version=${{ steps.gitversion.outputs.semVer }} /p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }} /p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}

      - name: Upload a Other Artifacts
        if: always()
        uses: actions/upload-artifact@v2.2.3
        with:
          name: Other
          path: 'artifacts/**/*'

      - name: Upload a NuGet Artifacts
        uses: actions/upload-artifact@v2.2.3
        with:
          name: NuGet
          path: '**/*.nupkg'
